apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sora
  labels:
    app: sora
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sora
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
