{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sora.secretName" . }}
  labels:
    {{- include "sora.labels" . | nindent 4 }}
type: Opaque
stringData:
  AI_API_KEY: {{ .Values.secrets.aiApiKey | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookURL | quote }}
  SLACK_SIGNING_SECRET: {{ .Values.secrets.slackSigningSecret | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.secrets.telegramChatID | quote }}
  PAGERDUTY_KEY: {{ .Values.secrets.pagerdutyKey | quote }}
{{- end }}
